/**
 * ChatNotes - PDF Exporter
 * Generates vector-crisp, multi-page PDFs using browser Paged Media CSS.
 * Preserves selectable text, code syntax, tables, custom page sizes, headers, and footers.
 */

const PdfExporter = {
  /**
   * Export document to PDF via browser paged printing
   * @param {object} doc Structured document model
   * @param {string} renderedHtml Inner HTML of document body
   * @param {string} templateCss Embedded CSS styles
   * @param {object} settings Customization preferences
   */
  export(doc, renderedHtml, templateCss = '', settings = {}) {
    const title = doc.title || 'ChatNotes Document';
    const pageSize = settings.pageSize || 'A4';
    const orientation = settings.orientation || 'portrait';
    const font = settings.font || 'Inter';

    // Calculate margins
    const marginMap = {
      small: '12mm',
      normal: '20mm',
      large: '28mm'
    };
    const marginValue = marginMap[settings.margins] || '20mm';

    // Build hidden print iframe to prevent UI disruption
    let iframe = document.getElementById('chatnotes-print-frame');
    if (!iframe) {
      iframe = document.createElement('iframe');
      iframe.id = 'chatnotes-print-frame';
      iframe.style.position = 'fixed';
      iframe.style.right = '0';
      iframe.style.bottom = '0';
      iframe.style.width = '0';
      iframe.style.height = '0';
      iframe.style.border = '0';
      document.body.appendChild(iframe);
    }

    const frameDoc = iframe.contentWindow.document;
    frameDoc.open();
    frameDoc.write(`<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>${title}</title>
  <style>
    @page {
      size: ${pageSize} ${orientation};
      margin: ${marginValue};
      @top-center {
        content: "${settings.headerStyle === 'title' ? title : ''}";
        font-family: sans-serif;
        font-size: 9pt;
        color: #94a3b8;
      }
      @bottom-center {
        content: "${settings.footerStyle === 'page-numbers' ? 'Page ' counter(page) ' of ' counter(pages) : ''}";
        font-family: sans-serif;
        font-size: 9pt;
        color: #94a3b8;
      }
    }

    *, *::before, *::after {
      box-sizing: border-box;
      margin: 0;
      padding: 0;
    }

    body {
      font-family: '${font}', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      color: ${settings.textColor || '#0f172a'};
      background: #ffffff;
      line-height: 1.6;
      font-size: ${settings.fontSize || 14}px;
    }

    .chatnotes-document {
      width: 100%;
      background: #ffffff;
    }

    /* Embedded template styles */
    ${templateCss}

    /* Prevent awkward mid-element page breaks */
    .question-box,
    .key-points-box,
    pre,
    table,
    img,
    h1, h2, h3, h4 {
      page-break-inside: avoid;
      break-inside: avoid;
    }

    h1, h2, h3 {
      page-break-after: avoid;
      break-after: avoid;
    }

    /* Print header / footer emulation for browsers without CSS @page margins */
    .print-header {
      font-size: 10px;
      color: #94a3b8;
      border-bottom: 1px solid #e2e8f0;
      padding-bottom: 4px;
      margin-bottom: 16px;
      display: flex;
      justify-content: space-between;
    }

    .print-footer {
      font-size: 10px;
      color: #94a3b8;
      border-top: 1px solid #e2e8f0;
      padding-top: 4px;
      margin-top: 24px;
      text-align: center;
    }
  </style>
</head>
<body>
  ${settings.headerStyle === 'title' ? `
    <div class="print-header">
      <span>${title}</span>
      <span>${new Date().toLocaleDateString()}</span>
    </div>` : ''}

  <article class="chatnotes-document template-${settings.template || 'academic'}">
    ${renderedHtml}
  </article>

  ${settings.footerStyle !== 'none' ? `
    <div class="print-footer">
      Generated by ChatNotes &bull; 100% Client-Side Private Document
    </div>` : ''}
</body>
</html>`);
    frameDoc.close();

    // Trigger native browser print dialog after content is fully loaded
    setTimeout(() => {
      iframe.contentWindow.focus();
      iframe.contentWindow.print();
    }, 350);
  }
};

if (typeof module !== 'undefined' && module.exports) {
  module.exports = PdfExporter;
}
